//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SansarEmporiamApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerDetail
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string EmailID { get; set; }
        public string City { get; set; }
        public string CustomerAddress { get; set; }
        public string PurchaseItem { get; set; }
        public string PurchaseDate { get; set; }
        public string TotalAmount { get; set; }
        public string PaidAmount { get; set; }
        public string DueDate { get; set; }
        public string RemainderMessage { get; set; }
        public string Balance { get; set; }
    }
}
