//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SansarEmporiamApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockDetail
    {
        public int StockID { get; set; }
        public string WholeSellPrice { get; set; }
        public string SellingPrice { get; set; }
        public string NumberOfCount { get; set; }
        public string Weight { get; set; }
        public string ItemName { get; set; }
    }
}
