//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SansarEmporiamApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWholeSellerDetail
    {
        public int ShopID { get; set; }
        public string ShopName { get; set; }
        public string OwnerName { get; set; }
        public string ShopAddress { get; set; }
        public string RegistrationNumber { get; set; }
        public string MobileNumber { get; set; }
    }
}
